name: brainwired_machine_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  map_launcher: ^3.3.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.11
  riverpod_lint: ^2.3.12
  riverpod_generator: ^2.4.2
  freezed: ^2.5.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
